#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="dokku/$APP"
FILE="public/assets/manifest-123.json"

COMMAND=$(cat <<EOF
touch /app/$FILE
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)

id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
