#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

dokku_log_info1_quiet "Skipping assets and js related tasks for Rails"

APP="$1"
IMAGE="dokku/$APP"

COMMAND=$(cat <<EOF
# ensure nodejs pack won't be run
sed -i '/nodejs/d' .buildpacks
# ensure assets:precompile won't run
touch /app/public/assets/manifest-random.json
# wait so that docker run has not exited before docker attach
sleep 1
EOF
)

id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
